
function vehicle = Alpha ()

vehicle.name = "Alpha";

vehicle.stage  = [
 struct( ...
    'm_dry',   2895, ...
    'm_prop',  43367, ...
    'thrust',  801000, ...
    'isp',     295.6, ...
    'Cd',      0.3, ...
    'A',       3.8, ...
    'A_exit',  0.283 , ...
    'pld_guess', 500) %lower bounds

struct( ...
    'm_dry',   910, ...
    'm_prop',  6835, ...
    'thrust',  70100, ...
    'isp',     322, ...
    'Cd',      0.3, ...
    'A',       3.8, ...
    'A_exit',  0 , ...
    'pld_guess', 1200) %upper bounds
];

%SSO
vehicle.performance.altitude=[
500e3
    ];

vehicle.performance.payload=[
630
 ];
end